name: Release

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: google-gemini-desktop-app-linux-amd64-v0.0.1, platform: linux/amd64, os: ubuntu-latest},
          {name: google-gemini-desktop-app-windows-amd64-v0.0.1, platform: windows/amd64, os: windows-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags 
        run: git fetch --tags --force

      - name: Calculate next version
        id: version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          latest_version=${latest_tag#v}
          major=$(echo $latest_version | cut -d. -f1)
          minor=$(echo $latest_version | cut -d. -f2)
          patch=$(echo $latest_version | cut -d. -f3)
          next_patch=$((patch + 1))
          new_version="v$major.$minor.$next_patch"
          echo "Calculated next version: $new_version"
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
          package: true

      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: build/bin/${{ matrix.build.name }}
      #     asset_name: ${{ matrix.build.name }}
      #     tag: v0.0.1
      #     overwrite: true
      #     body: "This is my release text"